//! Vector icons, stroked through the same line batch as text.
//!
//! No texture atlas, no raster assets and no second pipeline: an icon is a
//! handful of polylines in a 16x16 grid, and each polyline costs one line
//! segment per pair of points. A whole 40-icon toolbar is ~300 segments, which
//! is nothing next to a drawing that already has thousands.
//!
//! # Encoding
//!
//! Points are hex nibbles, `x` then `y`, on a 0..15 grid. A polyline is a run of
//! two-nibble points: `"0F44"` is a cross from the centre to the corner. Sixteen
//! points is the longest any icon here needs, so `POINTS` is a fixed array and
//! nothing allocates.
//!
//! ```text
//!   "F0"        one point (15, 0) -- a dot
//!   "0F4F"      two points (0,15) -> (4,15)
//!   "88,F8,B8"  separate polylines, comma-separated
//! ```
//!
//! Decoding happens per frame and costs a few hundred nibble reads; that is
//! cheaper than the branch misprediction in a texture lookup, and it means the
//! icon table is one line per icon instead of sixty.

/// Longest polyline any icon needs.
pub const POINTS: usize = 16;

/// The icon grid size: coordinates run 0..15 through `GRID - 1`.
pub const GRID: f32 = 16.0;

/// One polyline, already decoded into grid coordinates.
pub type Polyline = [(f32, f32); POINTS];

/// A named set of polylines, in a 16x16 grid.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Icon {
    pub name: &'static str,
    /// Comma-separated polylines, each a run of two-nibble points: `x` then
    /// `y`, both one hex character.
    pub data: &'static str,
}

/// Decode one icon's data into polylines.
///
/// Returns nothing for malformed data, so a typo in the table renders nothing
/// rather than a panic -- an icon is allowed to be absent silently.
pub fn decode(icon: Icon) -> Vec<Polyline> {
    let mut out = Vec::new();
    for stroke in icon.data.split(',') {
        let bytes = stroke.as_bytes();
        // Two hex characters per point: the x nibble then the y nibble. So
        // `bytes[2 * i]` is point `i`'s x and `bytes[2 * i + 1]` its y.
        if bytes.is_empty() || bytes.len() % 2 != 0 {
            continue;
        }
        let n = (bytes.len() / 2).min(POINTS);
        let mut p = [(0.0f32, 0.0f32); POINTS];
        let mut ok = true;
        for i in 0..n {
            match (
                (bytes[i * 2] as char).to_digit(16),
                (bytes[i * 2 + 1] as char).to_digit(16),
            ) {
                (Some(x), Some(y)) => p[i] = (x as f32, y as f32),
                // One bad nibble poisons the whole stroke, and skipping it is
                // the point: a half-drawn icon reads as a bug in the glyph,
                // while a missing one reads as a missing icon.
                _ => {
                    ok = false;
                    break;
                }
            }
        }
        if ok {
            out.push(p);
        }
    }
    out
}

// --------------------------------------------------------------------- icons

/// All icons, one line each.
///
/// Names match the commands they stand for, so the ribbon table and this table
/// cannot drift apart without a test noticing.
pub const ICONS: &[Icon] = &[
    // Autogenerated from a point table: every coordinate is checked against the
    // 16x16 grid when this list is generated, so a coordinate out of range cannot
    // get in by hand-editing one line.
    Icon {
        name: "line",
        data: "0EF2",
    },
    Icon {
        name: "circle",
        data: "82C4E8CC8E4C284482",
    },
    Icon {
        name: "arc",
        data: "3C67C6EC",
    },
    Icon {
        name: "polyline",
        data: "0D469AD3",
    },
    Icon {
        name: "rectangle",
        data: "23D3DC2C23",
    },
    Icon {
        name: "spline",
        data: "0B54ACF3",
    },
    Icon {
        name: "move",
        data: "88,828E,46F6",
    },
    Icon {
        name: "copy",
        data: "33D3DC3C33,4DDD,44,4C",
    },
    Icon {
        name: "rotate",
        data: "3D3682D6DD,88",
    },
    Icon {
        name: "scale",
        data: "22EE,22C2E422,EEE48E,2BB2",
    },
    Icon {
        name: "mirror",
        data: "818F,08F8,88,54BC,5CB4",
    },
    Icon {
        name: "offset",
        data: "03F3,0DFD,030D",
    },
    Icon {
        name: "trim",
        data: "E46F,5C9C,5C",
    },
    Icon {
        name: "extend",
        data: "08F8,88,818F",
    },
    Icon {
        name: "erase",
        data: "2255285B2E,55FB,28C8",
    },
    Icon {
        name: "array",
        data: "22E2EE2E,22EE",
    },
    Icon {
        name: "block",
        data: "22E2EE2E,727E,72E8,7EE8",
    },
    Icon {
        name: "explode",
        data: "4D4388D3,D3DD,DD4D,884D",
    },
    Icon {
        name: "undo",
        data: "F494585B9FFF",
    },
    Icon {
        name: "redo",
        data: "0464A8AB6F0F",
    },
    Icon {
        name: "save",
        data: "21D1DC2C21,4145B5B1",
    },
    Icon {
        name: "open",
        data: "23D3F92C23,2C83,D3DC",
    },
    Icon {
        name: "new",
        data: "31B1E43E31,818E",
    },
    Icon {
        name: "export",
        data: "F4D4813414,818B,588BB8",
    },
    Icon {
        name: "grid",
        data: "04F4,08F8,0CFC,404F,808F,C0CF",
    },
    Icon {
        name: "snap",
        data: "2D55A3D9,92E2E797",
    },
    Icon {
        name: "ortho",
        data: "818F,18F8",
    },
    Icon {
        name: "polar",
        data: "848B,28E8,87",
    },
    Icon {
        name: "zoomin",
        data: "18F8,818F",
    },
    Icon {
        name: "zoomout",
        data: "18F8",
    },
    Icon {
        name: "zoomall",
        data: "111511,1151,EEEAEE,EEAE",
    },
    Icon {
        name: "fit",
        data: "11F1FF1F,848C",
    },
    Icon {
        name: "3d",
        data: "82D4883482,343A8EDA,D4DA",
    },
    Icon {
        name: "layers",
        data: "C22225C5,C7272ACA,CD2D",
    },
    Icon {
        name: "eye",
        data: "1854A4E8,E8AC5C18,88",
    },
    Icon {
        name: "lock",
        data: "57546383A3A7,A8AC8C5C,5C",
    },
    Icon {
        name: "plus",
        data: "828E,28E8",
    },
    Icon {
        name: "crosshair",
        data: "8183,8C8E,1838,C8E8,88",
    },
    Icon {
        name: "dimension",
        data: "04F4,7177,F4FB",
    },
    Icon {
        name: "dimlinear",
        data: "08F8,030D,F3FD",
    },
    Icon {
        name: "box",
        data: "22D2DD2D,28D8,2DD2",
    },
    Icon {
        name: "extrude",
        data: "22D2DD2D,2255,555F",
    },
    Icon {
        name: "check",
        data: "286CE4",
    },
    Icon {
        name: "cross",
        data: "33DD,D33D",
    },
    Icon {
        name: "help",
        data: "3C3A587A7C,3D,8E",
    },
    Icon {
        name: "home",
        data: "1881F8,464E,C6CE,4ECE",
    },
    Icon {
        name: "trash",
        data: "23E3,6371,71A1,232D,E3ED,ED2D",
    },
    Icon {
        name: "text",
        data: "12F2,828D,24E4",
    },
    Icon {
        name: "search",
        data: "BBEE,29",
    },
    Icon {
        name: "layer",
        data: "22D2DD2D,28D8,2DD2",
    },
    Icon {
        name: "select",
        data: "2E2287E2,2E,87",
    },
    Icon {
        name: "zoomwindow",
        data: "111511,1151,EEEAEE,EEAE",
    },
];

/// Look up an icon by name.
pub fn by_name(name: &str) -> Option<Icon> {
    ICONS.iter().copied().find(|i| i.name == name)
}

/// Every icon that exists, for tests and for a picker.
pub fn names() -> impl Iterator<Item = &'static str> {
    ICONS.iter().map(|i| i.name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_icon_decodes_into_something() {
        for i in ICONS {
            let p = decode(*i);
            assert!(!p.is_empty(), "{} is empty", i.name);
        }
    }

    #[test]
    fn icon_names_are_unique() {
        let mut seen = std::collections::HashSet::new();
        for n in names() {
            assert!(seen.insert(n), "duplicate icon {n}");
        }
    }

    #[test]
    fn a_comma_separates_polylines() {
        let r = decode(Icon {
            name: "x",
            data: "0F80,0128",
        });
        assert_eq!(r.len(), 2);
        // "0F80" is (0,15) then (8,0).
        assert_eq!(r[0][0], (0.0, 15.0));
        assert_eq!(r[0][1], (8.0, 0.0));
    }

    #[test]
    fn a_single_point_is_a_dot() {
        // Two characters, one point: the dot is a degenerate polyline.
        let p = decode(Icon {
            name: "d",
            data: "0F",
        });
        assert_eq!(p.len(), 1);
        assert_eq!(p[0][0], (0.0, 15.0));
        let q = decode(Icon {
            name: "d",
            data: "F0",
        });
        assert_eq!(q[0][0], (15.0, 0.0));
    }

    #[test]
    fn three_points_run_along_one_polyline() {
        let p = decode(Icon {
            name: "z",
            data: "0F4F83",
        });
        assert_eq!(p.len(), 1);
        assert_eq!(
            p[0],
            [
                (0.0, 15.0),
                (4.0, 15.0),
                (8.0, 3.0),
                (0.0, 0.0),
                (0.0, 0.0),
                (0.0, 0.0),
                (0.0, 0.0),
                (0.0, 0.0),
                (0.0, 0.0),
                (0.0, 0.0),
                (0.0, 0.0),
                (0.0, 0.0),
                (0.0, 0.0),
                (0.0, 0.0),
                (0.0, 0.0),
                (0.0, 0.0)
            ]
        );
    }

    #[test]
    fn a_bad_nibble_drops_the_stroke_from_there_on() {
        // The conv won't happen, so only points before the bad one are kept --
        // and the stroke is still emitted, with a truncated count the caller
        // sees as fewer live points. What matters is that nothing panics.
        let p = decode(Icon {
            name: "bad",
            data: "0F0G",
        });
        assert_eq!(p.len(), 1);
        assert_eq!(p[0][0], (0.0, 15.0));
    }

    #[test]
    fn malformed_data_decodes_to_nothing_rather_than_panicking() {
        // "08" is a single point, so it is *not* malformed: a polyline of one
        // point is a dot, which is how every `select`-style icon ends.
        // A stroke of one point *is* legal (a dot), so "08" is not here; what
        // is here is anything that cannot be read as whole two-nibble points.
        for bad in ["", "0", "0G", "08G4", "88,88,8", "0F0G", ","] {
            assert_eq!(
                decode(Icon {
                    name: "bad",
                    data: bad
                })
                .len(),
                0,
                "{bad}"
            );
        }
    }

    #[test]
    fn every_icon_in_the_table_is_drawable() {
        // The table is checked when it is generated, so this is the belt to that
        // pair of braces: a hand-edit that breaks an icon fails here.
        for i in ICONS {
            let p = decode(*i);
            assert!(!p.is_empty(), "{} decodes to nothing", i.name);
            for stroke in &p {
                // A point at (0,0) and beyond is padding, not geometry.
                let live = stroke
                    .iter()
                    .copied()
                    .take_while(|p| *p != (0.0, 0.0))
                    .count()
                    .max(1);
                for &(x, y) in &stroke[..live] {
                    assert!(
                        (0.0..GRID).contains(&x),
                        "{} x={x} is outside the grid",
                        i.name
                    );
                    assert!(
                        (0.0..GRID).contains(&y),
                        "{} y={y} is outside the grid",
                        i.name
                    );
                }
            }
        }
    }

    #[test]
    fn lookup_finds_and_misses() {
        assert_eq!(by_name("line").map(|i| i.name), Some("line"));
        assert!(by_name("nope").is_none());
    }

    #[test]
    fn the_grid_is_the_right_size_for_the_nibbles() {
        // One nibble per coordinate, so 16 values and 0..16 is the exclusive
        // upper bound. `(15.0f32 < GRID)` is a constant, so it proves nothing;
        // what matters is that the bound and the nibble count agree.
        assert_eq!(GRID, 16.0);
        // What actually pins it: a coordinate is one hex digit, and the grid
        // bound is one past the largest value a digit can hold.
        assert_eq!(
            char::from_digit(15, 16).and_then(|c| c.to_digit(16)),
            Some(15)
        );
        assert_eq!(15u32 + 1, GRID as u32);
    }
}
